### ISSUE TITLE
Enhacements 

### ISSUE THREAD

**Issue by gocanto** [gocanto/grid-search#1]
## Todo

- [x] Activate the filter.
- [x] Fix styles for:
     - [x]  Price.
     - [x] Photo.
     - [x] Identifier.
- [x] Improve the top bar.
- [x] Improve favicon.
- [x] Read the assignment file and make sure the app covers everything.
- [x] Make more cols searchable.
- [x] try to check if an image is broken and replace it with a place holder.
- [x] Allow for dynamic imports.

**Comment by gocanto** [comment]
# Coding Task

### Description:
You will have to build a small Vue.js application using a data source as a text file  located on the folder `/api/mocks/products.json` contains a json object with a set of data
The root of the json file contains an array of objects called `products`
Each Product has a set of data as name, link, image, price and description

### Rules:

- You will have access to the internet and feel free to find anything you need by searching the internet. Attempt to fulfill each of the requirements below in the order specified.
- This is not about speed and it is OK if you cannot finish all requirements in allotted time. However, be sure to organize your code structure accordingly and design/code in a way that is considered a production quality deliverable.
- This is not about how much you can get done in a small amount of time, rather is about producing working, well written code.
- We will not be evaluating your design, but yes how the UX is presented.
- If we can’t run your application we will not able to evaluate your task
- You need to deliver the task to us in a Zip file without the node dependencies

### Requirements:
- VUE.js must be used to create a web app to utilize the provided json file
- The products contained in the array needs to be displayed with all the information available
- A fully functionally search bar needs to be present at the header
- A detail page for each product

### Restrictions:
- You are not allowed to change the products JSON file
- The application needs to run following your instructions on the Readme.md file
- You will have 1 week to complete the task
- The clock will start when the task is sent
